### ISSUE TITLE
result: undefined

### ISSUE THREAD

**Issue by oroszlanyzsolt** [michaelrhodes/css-combine#2]
On Windows 7 (x64), Node.js v0.10.35 installed css-combine installed globaly after entering css-combine main.css > main.comb.css or just css-combine main.css returns undefined.
The main.css contains:

html {
font-size: 100%;
}

body {
margin: 0;
}

**Comment by michaelrhodes** [comment]
Thanks, I’m looking into it now :)

**Comment by michaelrhodes** [comment]
I just published 0.1.8 which should hopefully resolve this issue.

**Comment by oroszlanyzsolt** [comment]
Thank you @michaelrhodes it works like magic now! Awesome tool.

**Comment by michaelrhodes** [comment]
Good to hear!
